#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: builder
spec:
  serviceAccountRef:
    name: kpack-service-account
    namespace: kpack
  tag: #@ data.values.builder.tag
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/python
  - group:
    - id: paketo-buildpacks/nginx
  - group:
    - id: paketo-buildpacks/dotnet-core
  - group:
    - id: paketo-buildpacks/procfile
  - group:
    - id: paketo-buildpacks/ruby
