apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: go-kaniko-01
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/image-builder: kaniko
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/digitalocean/sample-dockerfile
      ref:
        branch: main
