apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-core-demo-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/vrabbi/example-dotnet-app
      ref:
        branch: main
