apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kpack-config.tap.oss.0.5.2
spec:
  licenses:
  - Apache 2.0
  refName: kpack-config.tap.oss
  releaseNotes: kpack config using paketo buildpacks for version 0.5.0 https://github.com/pivotal/kpack/releases/tag/v0.5.0
  releasedAt: "2021-12-13T12:00:00Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/vrabbi/kpack-config-package:0.5.2
      template:
      - ytt:
          paths:
          - config/
  valuesSchema:
    openAPIv3:
      properties:
        builder:
          type: object
          additionalProperties: false
          properties:
            tag:
              type: string
              default: harbor.tap.oss/library/builder
              description: The Image Tag for the builder in the registry
        registry:
          type: object
          additionalProperties: false
          properties:
            username:
              type: string
              default: admin
              description: Registry Username for storing the cluster builder artifacts
            password:
              type: string
              default: Harbor12345
              description: Registry Password for storing the cluster builder artifacts
            server:
              type: string
              default: harbor.tap.oss
              description: Registry Server for storing the cluster builder artifacts
      title: kpack-config.tap.oss 0.5.0 values schema
  version: 0.5.2
