#@ load("@ytt:data", "data")
#@ if hasattr(data.values, "testing"):
#@ if hasattr(data.values.testing, "configure"):
#@ if data.values.testing.configure == True:
---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: test
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: $(workload.metadata.name)$
    spec:
      serviceAccountName: $(workload.spec.serviceAccountName)$
      runTemplateRef:
        name: tekton-taskrun
      selector:
        resource:
          apiVersion: tekton.dev/v1beta1
          kind: Task
        matchingLabels:
          apps.tanzu.vmware.com/task: test
      inputs:
        source: $(source)$
        params:
          - name: blob-url
            value: $(source.url)$
          - name: blob-revision
            value: $(source.revision)$
---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-taskrun
spec:
  outputs:
    url: spec.params[?(@.name=="blob-url")].value
    revision: spec.params[?(@.name=="blob-revision")].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-
    spec:
      taskRef: {name: $(selected.metadata.name)$}
      params: $(runnable.spec.inputs.params)$
---
#@ install = True
#@ for i in data.values.disable_specific_supply_chains:
#@   if i == "ootb-testing-supply-chain":
#@     install = False
#@   end
#@ end
#@ if install == True:
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: ootb-testing-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web
    app.tanzu.vmware.com/has-tests: "true"
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: source-tester
      templateRef:
        kind: ClusterSourceTemplate
        name: test
      sources:
        - resource: source-provider
          name: source
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      params:
        - name: image_prefix
          value: #@ data.values.image_prefix
      sources:
        - resource: source-tester
          name: source
    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - resource: image-builder
          name: image
#@ end
#@ end
#@ end
#@ end
