apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kpack.tap.oss.0.5.0
spec:
  capacityRequirementsDescription: Cluster with nodes > 50GB ephemeral storage, Registry
    > 5GB available space
  refName: kpack.tap.oss
  releaseNotes: https://github.com/pivotal/kpack/releases/tag/v0.5.0
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tce/kpack@sha256:8e83dca61e3574ea1bb0ea7a6aabec1cb317eebbedd212439f70b698df6a4ba5
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      properties:
        http_proxy:
          description: the HTTP proxy to use for network traffic
          type: string
        https_proxy:
          description: the HTTPS proxy to use for network traffic.
          type: string
        kp_default_repository:
          description: docker repository
          examples:
          - registry.io/kpack
          type: string
        kp_default_repository_password:
          description: registry password
          examples:
          - password
          type: string
        kp_default_repository_username:
          description: registry username
          examples:
          - janedoe@vmware.com
          type: string
        no_proxy:
          description: A comma-separated list of hostnames, IP addresses, or IP ranges
            in CIDR format that should not use a proxy
          type: string
      title: kpack.tanzu.vmware.com values schema
  version: 0.5.0
