apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: service-bindings.tap.oss.0.6.0
spec:
  refName: service-bindings.tap.oss
  version: 0.6.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/vrabbi/service-bindings-package@sha256:e8f52ce61238d3b3f16f0ce0a2f1ae13a4e62e97f0c948457de83025760b66a6
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/service-bindings.yaml
      - ytt:
          paths:
          - '-'
          - bundle.yaml
      deploy:
      - kapp: {}
