apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-demo-app
  labels:
    app.tanzu.vmware.com/workload-type: web
    app.tanzu.vmware.com/gitops: "true"
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/vrabbi/python-demo-app.git
      ref:
        branch: master
