apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: go-demo-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/gitops: "true"
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/kontinue/hello-world
      ref:
        branch: main
  build:
    env:
      - name: CGO_ENABLED
        value: "0"
