apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-group: cartographer
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: cartographer.tap.oss
    versionSelection:
      constraints: 0.2.1

