#@ load("@ytt:data", "data")
#@ install = True
#@ for i in data.values.disabled_packages:
#@   if i == "cartographer.tap.oss":
#@     install = False
#@   end
#@ end
#@ if install == True:
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-group: cartographer
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: cartographer.tap.oss
    versionSelection:
      constraints: 0.2.1
#@ end
