apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: cert-manager
    kapp.k14s.io/change-rule: delete before deleting serviceaccount
  name: cert-manager
  namespace: tap-oss
spec:
  packageRef:
    refName: cert-manager.tap.oss
    versionSelection:
      constraints: 1.6.1
      prereleases: {}
  serviceAccountName: tap-oss-install-sa
