#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ install = True
#@ for i in data.values.disabled_packages:
#@   if i == "cert-injection-webhook.tap.oss":
#@     install = False
#@   end
#@ end
#@ if install == True:
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-injection-webhook
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: cert-injection-webhook.tap.oss
    versionSelection:
      constraints: 0.1.0
  values:
  - secretRef:
      name: cert-injection-webhook-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-injection-webhook-values
  namespace: tap-oss
stringData:
  values.yaml: #@ yaml.encode(data.values.cert_injection_webhook)
#@ end
