#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ install = True
#@ for i in data.values.disabled_packages:
#@   if i == "contour.tap.oss":
#@     install = False
#@   end
#@ end
#@ if install == True:
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: contour
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
  name: contour
  namespace: tap-oss
spec:
  packageRef:
    refName: contour.tap.oss
    versionSelection:
      constraints: 1.19.1
      prereleases: {}
  serviceAccountName: tap-oss-install-sa
  #@ if data.values.contour.envoy.service.type != "LoadBalancer":
  values:
  - secretRef:
      name: contour-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
  namespace: tap-oss
stringData:
  values.yaml: #@ yaml.encode(data.values.contour)
#@ end
#@ end
