#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ install = True
#@ for i in data.values.disabled_packages:
#@   if i == "knative-serving.tap.oss":
#@     install = False
#@   end
#@ end
#@ if install == True:
apiVersion: v1
data:
  config-map-overlay.yaml: I0AgbG9hZCgiQHl0dDpvdmVybGF5IiwgIm92ZXJsYXkiKQoKI0BvdmVybGF5L21hdGNoIGJ5PW92ZXJsYXkuc3Vic2V0KHsia2luZCI6IkNvbmZpZ01hcCJ9KSwgZXhwZWN0cz0iMSsiCi0tLQptZXRhZGF0YToKICAjQG92ZXJsYXkvbWF0Y2ggbWlzc2luZ19vaz1UcnVlCiAgYW5ub3RhdGlvbnM6CiAgICAjQG92ZXJsYXkvbWF0Y2ggbWlzc2luZ19vaz1UcnVlCiAgICBrYXBwLmsxNHMuaW8vdXBkYXRlLXN0cmF0ZWd5OiBza2lwCg==
kind: Secret
metadata:
  name: knative-config-map-overlay
  namespace: tap-oss
---
apiVersion: v1
data:
  template.yaml: I0AgbG9hZCgiQHl0dDpvdmVybGF5IiwgIm92ZXJsYXkiKQoKI0BvdmVybGF5L21hdGNoIGJ5PW92ZXJsYXkuc3Vic2V0KHsia2luZCI6IkNvbmZpZ01hcCIsICJtZXRhZGF0YSI6IHsibmFtZSI6ICJjb25maWctbmV0d29yayJ9fSkKLS0tCm1ldGFkYXRhOgogIGFubm90YXRpb25zOgogICAgI0BvdmVybGF5L21hdGNoIG1pc3Npbmdfb2s9VHJ1ZQogICAga2FwcC5rMTRzLmlvL3VwZGF0ZS1zdHJhdGVneTogc2tpcApkYXRhOgogICNAb3ZlcmxheS9tYXRjaCBtaXNzaW5nX29rPVRydWUKICAjQHlhbWwvdGV4dC10ZW1wbGF0ZWQtc3RyaW5ncwogIGRvbWFpbi10ZW1wbGF0ZTogInt7Lk5hbWV9fS17ey5OYW1lc3BhY2V9fS57ey5Eb21haW59fSIK
kind: Secret
metadata:
  name: knative-domain-template-overlay
  namespace: tap-oss
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: knative
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    kapp.k14s.io/change-rule.contour: "upsert after upserting contour"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: knative-domain-template-overlay
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: knative-config-map-overlay
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: knative-serving.tap.oss
    versionSelection:
      constraints: 1.0.0
  values:
  - secretRef:
      name: knative-serving-values
---
#@ if data.values.knative.domain.type == "nip.io":
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: tap-oss
stringData:
  values.yaml: |
    domain:
      type: "nip.io"
#@ end
#@ if data.values.knative.domain.type == "sslip.io":
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: tap-oss
stringData:
  values.yaml: |
    domain:
      type: "sslip.io"
#@ end
#@ if data.values.knative.domain.type == "real":
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: tap-oss
stringData:
  values.yaml: #@ yaml.encode(data.values.knative)
#@ end
#@ end
