#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: knative
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    kapp.k14s.io/change-rule.contour: "upsert after upserting contour"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: knative-serving.tap.oss
    versionSelection:
      constraints: 1.0.0
  values:
  - secretRef:
      name: knative-serving-values
---
#@ if data.values.knative.domain.type == "nip.io":
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: tap-oss
stringData:
  values.yaml: |
    domain:
      type: "nip.io"
#@ end
#@ if data.values.knative.domain.type == "sslip.io":
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: tap-oss
stringData:
  values.yaml: |
    domain:
      type: "sslip.io"
#@ end
#@ if data.values.knative.domain.type == "real":
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: tap-oss
stringData:
  values.yaml: #@ yaml.encode(data.values.knative)
#@ end
