#@ load("@ytt:data", "data")
#@ install = True
#@ for i in data.values.disabled_packages:
#@   if i == "service-bindings.tap.oss":
#@     install = False
#@   end
#@ end
#@ if install == True:
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: service-bindings
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-group: service-bindings
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: service-bindings.tap.oss
    versionSelection:
      constraints: 0.6.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-bindings-ctrl-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: controller
  namespace: service-bindings
#@ end
