apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: service-bindings
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-group: service-bindings
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: service-bindings.tap.oss
    versionSelection:
      constraints: 0.6.0
