#@ load("@ytt:data", "data")
#@ install = True
#@ for i in data.values.disabled_packages:
#@   if i == "tekton.tap.oss":
#@     install = False
#@   end
#@ end
#@ if install == True:
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton-pipelines
  namespace: tap-oss
  annotations:
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-oss-install-sa
  packageRef:
    refName: tekton.tap.oss
    versionSelection:
      constraints: 0.32.1
#@ end
